### ISSUE TITLE
Update documentation for setting up with Docker

### ISSUE THREAD

**Issue by FedericoEsparza** [Human-Connection/Nitro-Documentation#4]
Add documentation for setting up with Docker:
https://docs.human-connection.org/nitro/backend/installation/docker
 
https://github.com/Human-Connection/Nitro-Documentation/blob/master/backend/installation/docker.md

```@tobi``` was interested in this ticket.

**Comment by Tirokk** [comment]
@roschaefer I just followed the [AV Daily Code Kickoff by Federico to install Nitro-Backend with Docker](https://www.youtube.com/watch?v=HCad5HmPdRs). I just recognised that the file „Nitro-Backend/docker-compose.yml“ in the actual HC Nitro-Backend repo is different to the one @FedericoEsparza used in the video and I have on my machine, but has the same version 3.7.

**Differences**

HC Nitro-Backend repo:
```
 neo4j:
    image: humanconnection/neo4j:latest
    build:
      context: neo4j
```

My and Federico's Nitro-Backend repo:
```
  neo4j:
    image: humanconnection/neo4j:latest
    build:
      context: .
      dockerfile: Dockerfile.neo4j
```

And HC Nitro-Backend repo has an additional line `MAPBOX_TOKEN`:
```
services:
    environment:
      - MAPBOX_TOKEN=pk.eyJ1IjoiaHVtYW4tY29ubmVjdGlvbiIsImEiOiJjajl0cnBubGoweTVlM3VwZ2lzNTNud3ZtIn0.KZ8KK9l70omjXbEkkbHGsQ
```

**Question**
As I have seen you just fixed some issues related to the Nitro-Backend Docker installation. Should I better use the newer version of HC Nitro-Backend repo for installation?
